#!/bin/bash
#SBATCH -p main
#SBATCH --ntasks=MY_DIR_NUMBER
#SBATCH --mem-per-cpu=2048
#SBATCH --time=0-5:00:00
#SBATCH --job-name=runname

for i in `seq 1 $SLURM_NTASKS`
do
    srun --nodes=1 --ntasks=1 --cpus-per-task=1 sh -c "(cd xxx/$i; sh tconcoord-docking)" &
done
# IMPORTANT must wait for all to finish, or all get killed
wait
